// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package message

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson4086215fDecodeProcessorMessage(in *jlexer.Lexer, out *NodeData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "history":
			out.NodeId = string(in.String())
		case "startTime":
			out.EntryTime = int64(in.Int64())
		case "endTime":
			out.ExitTime = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4086215fEncodeProcessorMessage(out *jwriter.Writer, in NodeData) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"history\":"
		out.RawString(prefix[1:])
		out.String(string(in.NodeId))
	}
	{
		const prefix string = ",\"startTime\":"
		out.RawString(prefix)
		out.Int64(int64(in.EntryTime))
	}
	{
		const prefix string = ",\"endTime\":"
		out.RawString(prefix)
		out.Int64(int64(in.ExitTime))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v NodeData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4086215fEncodeProcessorMessage(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v NodeData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4086215fEncodeProcessorMessage(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *NodeData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4086215fDecodeProcessorMessage(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *NodeData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4086215fDecodeProcessorMessage(l, v)
}
func easyjson4086215fDecodeProcessorMessage1(in *jlexer.Lexer, out *Message) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "hops":
			if in.IsNull() {
				in.Skip()
				out.Hops = nil
			} else {
				in.Delim('[')
				if out.Hops == nil {
					if !in.IsDelim(']') {
						out.Hops = make([]NodeData, 0, 2)
					} else {
						out.Hops = []NodeData{}
					}
				} else {
					out.Hops = (out.Hops)[:0]
				}
				for !in.IsDelim(']') {
					var v1 NodeData
					(v1).UnmarshalEasyJSON(in)
					out.Hops = append(out.Hops, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "workload":
			out.Workload = int(in.Int())
		case "payload":
			out.Payload = string(in.String())
		case "messageId":
			out.MessageId = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4086215fEncodeProcessorMessage1(out *jwriter.Writer, in Message) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"hops\":"
		out.RawString(prefix[1:])
		if in.Hops == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Hops {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"workload\":"
		out.RawString(prefix)
		out.Int(int(in.Workload))
	}
	{
		const prefix string = ",\"payload\":"
		out.RawString(prefix)
		out.String(string(in.Payload))
	}
	{
		const prefix string = ",\"messageId\":"
		out.RawString(prefix)
		out.String(string(in.MessageId))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Message) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4086215fEncodeProcessorMessage1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Message) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4086215fEncodeProcessorMessage1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Message) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4086215fDecodeProcessorMessage1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Message) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4086215fDecodeProcessorMessage1(l, v)
}
